### ISSUE TITLE
Java executable file for LRozenblyum Chess

### ISSUE THREAD

**Issue by ChessGUI** [lrozenblyum/chess#213]
Hello, can you accomplish the task to build a functional jar-file of LRozenblyum Chess please?

It is platform-independent and requires JRE http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html for different operation systems.

**Comment by lrozenblyum** [comment]
Hello yes for sure I can build it.
But do you mean a simple Jar that can be injected into UI like Winboard or something else?

**Comment by ChessGUI** [comment]
a simple jar file works with  WinBoard, ChessGUI and Arena cf. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list (CCWiki)

**Comment by lrozenblyum** [comment]
I uploaded a distribution (.zip archive) with the *.jar and dependencies and also with the .bat file to run Winboard with the engine.

The distributation is based on the first version that was considered rather stable to be marked as a pre-release (0.1). NOTE: soon 0.2 release will be created, with significant internal improvements.

Release itself with possibility to download:
https://github.com/lrozenblyum/chess/releases/tag/0.1

Direct download link
https://github.com/lrozenblyum/chess/releases/download/0.1/LeokomChess-0.1.zip

The .bat file contains important option -Dblack=Legal which should be turned ON otherwise a super-simple engine is in action. (in fact the LegalPlayer is not that sophisticated, its goal is to know gradually all the chess rules and then start to be more smart).

Also created a new issue for improvement #214 

Please tell me if any extra information is needed, I will be happy to help.

**Comment by lrozenblyum** [comment]
@ChessGUI The 0.2 release has been published. Thank you for your feedback which allowed to make it better and easier to use.

I'll appreciate any feedback.
